---
 - hosts: nodes
   tasks:  
    - name: Removing httpd
      yum: pkg=httpd state=absent
    - name: Removing index.html
      ansible.builtin.file: path=/var/www/html/index.html state=absent
    - name: Closing TCP port 80 on firewall
      firewalld: port=80/tcp permanent=yes state=disabled
...
