---
- name: creating user accounts
  hosts: nodes
  vars_files:
    - vars/userpass
  tasks: 
  - name: creating user accounts 
    user: 
      name: "{{ item.key }}"
      state: present
      update_password: on_create
      comment: "{{ item.key }}@example.com"
      home: "/home/{{ item.key }}"
      password: "{{ item.value.password | password_hash('sha512') }}"      
    with_dict: "{{ userpass }}"
...
